### PR TITLE
[PF-2199] add `cloudbuild.googleapis.com` and `containerregistry.googleapis.com`

### PR DESCRIPTION
**Pull request by ginaygoogle**
This PR comes from [PF-2199](https://broadworkbench.atlassian.net/browse/PF-2199)

Currently, the verily server supports `cloudbuild.googleapis.com` and`containerregistry.googleapis.com` api. 
In order to improve the test environment, we add the 2 APIs to the broad-dev server.

### CODE REVIEW

**Review by melissachang — COMMENTED** [review]
I chatted with @yuhuyoyo about this. This isn't correct, @yuhuyoyo can fill you in on the details

**Review by yonghaoy — CHANGES_REQUESTED** [review]
Modifying existing pool is not allowed, that will mess up the existing pool with mixed of project settings. 

1. Step1: Create new pools in each dir with the new API
2. Step 2: Wait for one week, after Buffer released to prod bump Rawls to use new pool example PR: https://github.com/broadinstitute/firecloud-develop/pull/3104
3. Step3: If we need to backfill existing projects, you need a script like this: https://github.com/broadinstitute/firecloud-develop/blob/dev/run-context/live/scripts/migrations/enable_lifesciences.sh

**Comment by melissachang** [comment]
As part of this, we should clearly document the process. https://github.com/DataBiosphere/terra-resource-buffer isn't very specific.

**Comment by yonghaoy** [comment]
> As part of this, we should clearly document the process. https://github.com/DataBiosphere/terra-resource-buffer isn't very specific.

We have documented how to upgrade buffer pools: https://github.com/DataBiosphere/terra-resource-buffer#upgrade-static-pool-configuration
For step 2 and 3, those are various by buffer clients, and out of buffer control. So probably some document in Rawls/TDR/WSM/AoU

**Comment by melissachang** [comment]
> > As part of this, we should clearly document the process. https://github.com/DataBiosphere/terra-resource-buffer isn't very specific.
> 
> We have documented how to upgrade buffer pools: https://github.com/DataBiosphere/terra-resource-buffer#upgrade-static-pool-configuration For step 2 and 3, those are various by buffer clients, and out of buffer control. So probably some document in Rawls/TDR/WSM/AoU

[I started a thread in #dsp-devops-champions](https://broadinstitute.slack.com/archives/CADM7MZ35/p1668115692848639)

**Pull request closed without merging**
