### PR TITLE
Add the vpc_sc_6 dev pool back in, still in use by Rawls

### PR DESCRIPTION
**Pull request by calbach**
From Rawls:

```
Server Error error: ErrorReport(Rawls,{"causes":[],"exceptionClass":"bio.terra.buffer.client.ApiException","message":"{\"message\":\"Invalid pool id: vpc_sc_v6.\",\"statusCode\":400,\"causes\":[]}","source":"rawls","stackTrace":
```

### CODE REVIEW

**Review by jaycarlton — APPROVED** [review]
Sorry about that.

**Comment by calbach** [comment]
No problem, I nearly shot myself in the foot with these configs last week as well

**Review by melissachang — APPROVED** [review]
Oops sorry

**Comment by calbach** [comment]
I didn't realize the tests were going to take ~1.5h here. If anyone has the authority / confidence to force merge this now that the basic unit tests have passed, that would be appreciated - our dev environment is currently broken. This is effectively a partial config rollback. (I'm not sure if the tests even interact with these pool configs or not).

**Comment by rtitle** [comment]
Unfortunately I don't think adding back a pool is allowed. From buffer dev logs:
```
Application run failed
java.lang.RuntimeException: An existing deactivated pool with duplicate id(id= vpc_sc_v6) found, please consider change the pool id.
	at bio.terra.buffer.service.pool.PoolService.lambda$updateFromConfig$4(PoolService.java:168)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at bio.terra.buffer.service.pool.PoolService.updateFromConfig(PoolService.java:139)
	at bio.terra.buffer.service.pool.PoolService.initialize(PoolService.java:70)
	at bio.terra.buffer.app.StartupInitializer.initialize(StartupInitializer.java:44)
	at bio.terra.buffer.app.configuration.ApplicationConfiguration.lambda$postSetupInitialization$0(ApplicationConfiguration.java:40)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:910)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at bio.terra.buffer.app.Main.main(Main.java:28)
```

Suggest we revert this and roll forward with https://github.com/broadinstitute/firecloud-develop/pull/2839.

**Pull request merged**
